### ISSUE TITLE
Extension not working at all?

### ISSUE THREAD

**Issue by yllekz** [njelich/LinkOff#23] opened 2021-08-23 15:40 UTC
**Describe the bug**
I'm not sure if LinkedIn updated recently, but it seems this extension is not working with the current version of the LinkedIn site. Posts are not being filtered, sorted, or anything, regardless of any option I select.

**To Reproduce**
1. Go to options menu
2. Play with any filters at all (ensure the core extension is enabled)
3. Observe nothing changes in the LinkedIn feed after reloading.

**Expected behavior**
The options should work

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 91

**Comment by alterednoah** [comment] 2021-09-02 16:53
Some of these issues should be fixed in 1.2.0. There have been major improvements to the extension, as well as bug fixes

**Comment by njelich** [comment] 2021-09-02 17:29
I have submitted the new version to the stores

**Comment by njelich** [comment] 2021-11-08 12:24
Thanks for the bug report :) Will check it out today - linkedin likely changed some of the classnames for the posts section.

**Comment by ValdoGhafoor** [comment] 2021-11-09 11:19
@FrankRay78 I can't reproduce on Brave
The extension sometimes needs scrolling a bit to be able to apply filters.
Have you tried that ?

**Comment by FrankRay78** [comment] 2021-11-09 12:05
> @FrankRay78 I can't reproduce on Brave The extension sometimes needs scrolling a bit to be able to apply filters. Have you tried that ?

I can try it again later on the original PC I used.  If it's still broken, I can take some screenshots showing that.

**Comment by ValdoGhafoor** [comment] 2021-11-09 12:18
Also, try to use gentle mode so you have a visual representation of hidden posts

**Comment by FrankRay78** [comment] 2021-11-09 14:28
I have tried it again, still not working.  

I had also wondered whether Brave shields and/or ad-block plus might be part of the issue. Disabled both to no affect.  

I hope the following screen shots help.

![img1](https://user-images.githubusercontent.com/52075808/140942150-88c932a3-441a-45f6-b3cd-64fa67b2554f.png)
![img2](https://user-images.githubusercontent.com/52075808/140942162-e59d06d2-8cc5-4b6f-859e-adf7e7f95873.png)

**Comment by ValdoGhafoor** [comment] 2021-11-24 13:48
Sorry for late answers and thank you for your feedbacks
I will take a look

**Comment by mpaluta** [comment] 2021-12-22 02:55
I reproduced this today as well.

MacOS Monterey 12.1
Chrome
Version 96.0.4664.110

**Comment by quadratecode** [comment] 2022-02-09 13:52
Further confirming that most of the filters are currently not working. Some options do have the indended effect such as "dark mode" and "hide the whole feed".

- OS: Windows 11
- Browser: Firefox 97

**Comment by suraniadi** [comment] 2022-03-13 15:42
Another confirmation that some options do not work anymore. A lot of them work correctly once you start scrolling. 
MacOS Monterey 12.1
Chrome

**Comment by njelich** [comment] 2022-03-14 12:23
I have improved the UX a bit, a lot of the complaints for the extension not working were coming from the fact we were waiting for a few posts to be loaded in before blocking. I have now made that clearer, as well as disabled the need when using dim mode (since it doesnt completely remove the posts but just collapses them)

**Closed by njelich** 2022-03-14 12:23 UTC
Labels: bug, released
