### ISSUE TITLE
Wide mode and Sort posts by recent -- not working after reloading page

### ISSUE THREAD

**Issue by fredbkamp** [njelich/LinkOff#49] opened 2023-03-04 00:22 UTC
**Describe the bug**
These excellent two features don't work when you reload the page. It's been like this for about 4-5 weeks.
Wide mode: I make it work by switching it off and on again.
Sort posts by recent: simply not working.

**To Reproduce**
1. Turn either feature on
2. Refresh the feed by reloading the page using the swirly arrow button on Chrome
3. See error

**Expected behavior**
What the features used to do :)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 110.0.5481.178 (Official Build) (64-bit)

**Additional context**
Thank you for this extension, it's brilliant.

**Comment by njelich** [comment] 2023-03-07 11:31
Thanks for the notification. I should sit down for a bug fixing session one of these days and take care of all outstanding issues.

**Comment by njelich** [comment] 2023-09-24 10:36
Please make a PR @jarp0l

**Comment by valdoryu** [comment] 2024-11-20 22:52
Sort posts by recent is now fixed #64 and will be in next release
I can't reproduce wide mode issue
Do you still experience it ?

**Comment by fredbkamp** [comment] 2024-11-21 02:11
It looks like sort by most recent was actually fixed by LinkedIn itself earlier this year.
Wide mode is working fine for me now. Will circle back if it acts up again.
Thank you.

**Closed** 2024-12-21 03:26 UTC
